### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by brennv** [brennv/autocomplete-python-jedi#2]
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Users/bj/.atom/packages/autocomplete-python-jedi/lib/provider.coffee:310

TypeError: Cannot read property 'split' of undefined
    at constructor._generateRequestConfig (/packages/autocomplete-python-jedi/lib/provider.coffee:310:56)
    at constructor.getSuggestions (/packages/autocomplete-python-jedi/lib/provider.coffee:400:16)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

**Comment by brennv** [comment]
Fixed with v1.9.1-1, refactored imports with https://github.com/brennv/autocomplete-python-jedi/commit/900eef2267bb984c6bb737d9c4f854c8f2f4dd34
