### ISSUE TITLE
Failed to activate the autocomplete-python-jedi package

### ISSUE THREAD

**Issue by JitsuP** [brennv/autocomplete-python-jedi#29]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [autocomplete-python-jedi](https://github.com/brennv/autocomplete-python-jedi) package 1.10.3-0

### Stack Trace

Failed to activate the autocomplete-python-jedi package

```
At Cannot read property 'providerManager' of null

TypeError: Cannot read property 'providerManager' of null
    at Object.consumeProvider (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:162485)
    at Object.consumeProvider_2 (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:162154)
    at Provider.provide (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1121906)
    at ServiceHub.provide (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3314762)
    at Package.activateServices (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3323048)
    at Package.activateNow (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3320024)
    at measure (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319348)
    at Package.measure (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3316958)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319208)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319151)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:382452)
    at ~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:941081
    at r (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:935687)
    at n (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1124813)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:1125019)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
  2x -8:16.2.0 core:confirm (input.hidden-input)
  6x -7:57.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python-jedi 1.10.3-0 
predawn-syntax 1.0.4 
script 3.25.0 
```

**Comment by JitsuP** [comment]
Also Could not install

Installing “autocomplete-python@1.16.0” failed.Hide output…

npm ERR! code E404
npm ERR! 404 Not Found: error-stack-parser@^2.0.4
